#Dockerfile for dht-package

#FROM <base-image>:<tag>
#Debian system with Go installed, copies the package source, fetches application dependencies, builds the program, and configures it to run on startup
FROM golang:on build

#Tell the container to listen on ports
EXPOSE 8080

